#!/bin/sh
if [ -z "$HOME" ] || [ ! -d "$HOME" ]; then
    [ -e debian/tests.home ] || mkdir debian/tests.home
    export HOME="$(pwd)/debian/tests.home"
    trap "rm -rf debian/tests.home" EXIT
fi
mkdir -p "$HOME"/.config || true
mkdir -p "$HOME"/.kde-unit-test || true
mkdir -p "$HOME"/.run || true
chmod 700 "$HOME"/.run
export XDG_RUNTIME_DIR="$HOME"/.run

xvfb-run -a dbus-launch --exit-with-session dh_auto_test
